// Copyright Epic Games, Inc. All Rights Reserved.

#include "MiraiPlayerBotController.h"

#include "AbilitySystemComponent.h"
#include "AbilitySystemGlobals.h"
#include "Engine/World.h"
#include "GameFramework/PlayerState.h"
#include "GameModes/MiraiGameMode.h"
#include "MiraiLogChannels.h"
#include "Perception/AIPerceptionComponent.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(MiraiPlayerBotController)

class UObject;

AMiraiPlayerBotController::AMiraiPlayerBotController(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	bWantsPlayerState = true;
	bStopAILogicOnUnposses = false;
}

//void AMiraiPlayerBotController::OnPlayerStateChangedTeam(UObject* TeamAgent, int32 OldTeam, int32 NewTeam)
//{
//	ConditionalBroadcastTeamChanged(this, IntegerToGenericTeamId(OldTeam), IntegerToGenericTeamId(NewTeam));
//}

void AMiraiPlayerBotController::OnPlayerStateChanged()
{
	// Empty, place for derived classes to implement without having to hook all the other events
}

void AMiraiPlayerBotController::BroadcastOnPlayerStateChanged()
{
	OnPlayerStateChanged();

	// Unbind from the old player state, if any
	FGenericTeamId OldTeamID = FGenericTeamId::NoTeam;
	if (LastSeenPlayerState != nullptr)
	{
		//if (IMiraiTeamAgentInterface* PlayerStateTeamInterface = Cast<IMiraiTeamAgentInterface>(LastSeenPlayerState))
		//{
		//	OldTeamID = PlayerStateTeamInterface->GetGenericTeamId();
		//	PlayerStateTeamInterface->GetTeamChangedDelegateChecked().RemoveAll(this);
		//}
	}

	// Bind to the new player state, if any
	FGenericTeamId NewTeamID = FGenericTeamId::NoTeam;
	//if (PlayerState != nullptr)
	//{
	//	if (IMiraiTeamAgentInterface* PlayerStateTeamInterface = Cast<IMiraiTeamAgentInterface>(PlayerState))
	//	{
	//		NewTeamID = PlayerStateTeamInterface->GetGenericTeamId();
	//		PlayerStateTeamInterface->GetTeamChangedDelegateChecked().AddDynamic(this, &ThisClass::OnPlayerStateChangedTeam);
	//	}
	//}

	// Broadcast the team change (if it really has)
	//ConditionalBroadcastTeamChanged(this, OldTeamID, NewTeamID);

	//LastSeenPlayerState = PlayerState;
}

void AMiraiPlayerBotController::InitPlayerState()
{
	Super::InitPlayerState();
	BroadcastOnPlayerStateChanged();
}

void AMiraiPlayerBotController::CleanupPlayerState()
{
	Super::CleanupPlayerState();
	BroadcastOnPlayerStateChanged();
}

void AMiraiPlayerBotController::OnRep_PlayerState()
{
	Super::OnRep_PlayerState();
	BroadcastOnPlayerStateChanged();
}

//void AMiraiPlayerBotController::SetGenericTeamId(const FGenericTeamId& NewTeamID)
//{
//	UE_LOG(LogMiraiTeams, Error, TEXT("You can't set the team ID on a player bot controller (%s); it's driven by the associated player state"), *GetPathNameSafe(this));
//}

//FGenericTeamId AMiraiPlayerBotController::GetGenericTeamId() const
//{
//	if (IMiraiTeamAgentInterface* PSWithTeamInterface = Cast<IMiraiTeamAgentInterface>(PlayerState))
//	{
//		return PSWithTeamInterface->GetGenericTeamId();
//	}
//	return FGenericTeamId::NoTeam;
//}

//FOnMiraiTeamIndexChangedDelegate* AMiraiPlayerBotController::GetOnTeamIndexChangedDelegate()
//{
//	return &OnTeamChangedDelegate;
//}


void AMiraiPlayerBotController::ServerRestartController()
{
	if (GetNetMode() == NM_Client)
	{
		return;
	}

	ensure((GetPawn() == nullptr) && IsInState(NAME_Inactive));

	if (IsInState(NAME_Inactive) || (IsInState(NAME_Spectating)))
	{
 		AMiraiGameMode* const GameMode = GetWorld()->GetAuthGameMode<AMiraiGameMode>();

		if ((GameMode == nullptr) /*|| !GameMode->ControllerCanRestart(this)*/)
		{
			return;
		}

		// If we're still attached to a Pawn, leave it
		if (GetPawn() != nullptr)
		{
			UnPossess();
		}

		// Re-enable input, similar to code in ClientRestart
		ResetIgnoreInputFlags();

		GameMode->RestartPlayer(this);
	}
}

//ETeamAttitude::Type AMiraiPlayerBotController::GetTeamAttitudeTowards(const AActor& Other) const
//{
//	if (const APawn* OtherPawn = Cast<APawn>(&Other)) {
//
//		if (const IMiraiTeamAgentInterface* TeamAgent = Cast<IMiraiTeamAgentInterface>(OtherPawn->GetController()))
//		{
//			FGenericTeamId OtherTeamID = TeamAgent->GetGenericTeamId();
//
//			//Checking Other pawn ID to define Attitude
//			if (OtherTeamID.GetId() != GetGenericTeamId().GetId())
//			{
//				return ETeamAttitude::Hostile;
//			}
//			else
//			{
//				return ETeamAttitude::Friendly;
//			}
//		}
//	}
//
//	return ETeamAttitude::Neutral;
//}

//void AMiraiPlayerBotController::UpdateTeamAttitude(UAIPerceptionComponent* AIPerception)
//{
//	if (AIPerception)
//	{
//		AIPerception->RequestStimuliListenerUpdate();
//	}
//}

void AMiraiPlayerBotController::OnUnPossess()
{
	// Make sure the pawn that is being unpossessed doesn't remain our ASC's avatar actor
	if (APawn* PawnBeingUnpossessed = GetPawn())
	{
		if (UAbilitySystemComponent* ASC = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(PlayerState))
		{
			if (ASC->GetAvatarActor() == PawnBeingUnpossessed)
			{
				ASC->SetAvatarActor(nullptr);
			}
		}
	}

	Super::OnUnPossess();
}

