// Copyright Epic Games, Inc. All Rights Reserved.

#include "MiraiGameState.h"

#include "AbilitySystem/MiraiAbilitySystemComponent.h"
#include "Async/TaskGraphInterfaces.h"
#include "GameFramework/GameplayMessageSubsystem.h"
#include "GameModes/MiraiExperienceManagerComponent.h"
#include "Messages/MiraiVerbMessage.h"
#include "Player/MiraiPlayerState.h"
#include "MiraiLogChannels.h"
#include "Net/UnrealNetwork.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(MiraiGameState)

class APlayerState;
class FLifetimeProperty;

extern ENGINE_API float GAverageFPS;


AMiraiGameState::AMiraiGameState(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;

	AbilitySystemComponent = ObjectInitializer.CreateDefaultSubobject<UMiraiAbilitySystemComponent>(this, TEXT("AbilitySystemComponent"));
	AbilitySystemComponent->SetIsReplicated(true);
	AbilitySystemComponent->SetReplicationMode(EGameplayEffectReplicationMode::Mixed);

	ExperienceManagerComponent = CreateDefaultSubobject<UMiraiExperienceManagerComponent>(TEXT("ExperienceManagerComponent"));

	ServerFPS = 0.0f;
}

void AMiraiGameState::PreInitializeComponents()
{
	Super::PreInitializeComponents();
}

void AMiraiGameState::PostInitializeComponents()
{
	Super::PostInitializeComponents();

	check(AbilitySystemComponent);
	AbilitySystemComponent->InitAbilityActorInfo(/*Owner=*/ this, /*Avatar=*/ this);
}

UAbilitySystemComponent* AMiraiGameState::GetAbilitySystemComponent() const
{
	return AbilitySystemComponent;
}

void AMiraiGameState::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);
}

void AMiraiGameState::AddPlayerState(APlayerState* PlayerState)
{
	Super::AddPlayerState(PlayerState);
}

void AMiraiGameState::RemovePlayerState(APlayerState* PlayerState)
{
	//@TODO: This isn't getting called right now (only the 'rich' AGameMode uses it, not AGameModeBase)
	// Need to at least comment the engine code, and possibly move things around
	Super::RemovePlayerState(PlayerState);
}

void AMiraiGameState::SeamlessTravelTransitionCheckpoint(bool bToTransitionMap)
{
	// Remove inactive and bots
	for (int32 i = PlayerArray.Num() - 1; i >= 0; i--)
	{
		APlayerState* PlayerState = PlayerArray[i];
		if (PlayerState && (PlayerState->IsABot() || PlayerState->IsInactive()))
		{
			RemovePlayerState(PlayerState);
		}
	}
}

void AMiraiGameState::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(ThisClass, ServerFPS);
	//DOREPLIFETIME_CONDITION(ThisClass, RecorderPlayerState, COND_ReplayOnly);
}

void AMiraiGameState::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (GetLocalRole() == ROLE_Authority)
	{
		ServerFPS = GAverageFPS;
	}
}

void AMiraiGameState::MulticastMessageToClients_Implementation(const FMiraiVerbMessage Message)
{
	if (GetNetMode() == NM_Client)
	{
		UGameplayMessageSubsystem::Get(this).BroadcastMessage(Message.Verb, Message);
	}
}

void AMiraiGameState::MulticastReliableMessageToClients_Implementation(const FMiraiVerbMessage Message)
{
	MulticastMessageToClients_Implementation(Message);
}

float AMiraiGameState::GetServerFPS() const
{
	return ServerFPS;
}

//void AMiraiGameState::SetRecorderPlayerState(APlayerState* NewPlayerState)
//{
//	if (RecorderPlayerState == nullptr)
//	{
//		// Set it and call the rep callback so it can do any record-time setup
//		RecorderPlayerState = NewPlayerState;
//		OnRep_RecorderPlayerState();
//	}
//	else
//	{
//		UE_LOG(LogMirai, Warning, TEXT("SetRecorderPlayerState was called on %s but should only be called once per game on the primary user"), *GetName());
//	}
//}

//APlayerState* AMiraiGameState::GetRecorderPlayerState() const
//{
//	// TODO: Maybe auto select it if null?
//
//	return RecorderPlayerState;
//}

//void AMiraiGameState::OnRep_RecorderPlayerState()
//{
//	OnRecorderPlayerStateChangedEvent.Broadcast(RecorderPlayerState);
//}